### ISSUE TITLE
✨ Adding infrastructure alerting for Production Servers

### ISSUE THREAD

**Issue by kyphutruong** [ministryofjustice/staff-infrastructure-certificate-services#47]
### User Story

As a cloud ops engineer
I need to be alerted of any unhealthy status of the production environment
So that we can attend to any issues that may arise in a timely manner

### Value / Purpose

To be alerted of the infrastructure

### Useful Contacts

Ky, Rich B

### Definition of Done

- [ ] To be alerted of CPU thresholds
- [ ] To be alerted of memory thresholds
- [ ] To be alerted of instances of not being online

**Comment by mitchdawson1982** [comment]
Metrics are already being obtained, this will require the alerting of said metrics & thresholds.
